// Auto-generated by scripts/generate_emoji_data.py; do not edit manually.
pub const FLAG_SMILEYS_EMOTION: u8 = 1 << 0;
pub const FLAG_SYMBOLS: u8 = 1 << 1;

#[derive(Clone, Copy)]
pub struct EmojiEntry {
    pub code: u32,
    pub flags: u8,
}

pub static EMOJI_DATA: &[EmojiEntry] = &[
    EmojiEntry {
        code: 0x00a9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x00ae,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x203c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2049,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2122,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2139,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2194,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2195,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2196,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2197,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2198,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2199,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x21a9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x21aa,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x231a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x231b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2328,
        flags: 0,
    },
    EmojiEntry {
        code: 0x23cf,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23e9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23ea,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23eb,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23ec,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23ed,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23ee,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23ef,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x23f1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x23f2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x23f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x23f8,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23f9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x23fa,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x24c2,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25aa,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25ab,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25b6,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25c0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25fb,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25fc,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25fd,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x25fe,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2600,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2601,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2602,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2603,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2604,
        flags: 0,
    },
    EmojiEntry {
        code: 0x260e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2611,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2614,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2615,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2618,
        flags: 0,
    },
    EmojiEntry {
        code: 0x261d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2620,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x2622,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2623,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2626,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x262a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x262e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x262f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2638,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2639,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x263a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x2640,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2642,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2648,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2649,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264d,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x264f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2650,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2651,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2652,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2653,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x265f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2660,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2663,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2665,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2666,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2668,
        flags: 0,
    },
    EmojiEntry {
        code: 0x267b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x267e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x267f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2692,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2693,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2694,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2695,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2696,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2697,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2699,
        flags: 0,
    },
    EmojiEntry {
        code: 0x269b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x269c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26a0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26a1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26a7,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26aa,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26ab,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26b0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26b1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26bd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26be,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26c4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26c5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26c8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26ce,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26d3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26d4,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x26e9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26ea,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26f9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x26fd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2702,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2705,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2708,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2709,
        flags: 0,
    },
    EmojiEntry {
        code: 0x270a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x270b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x270c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x270d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x270f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2712,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2714,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2716,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x271d,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2721,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2728,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2733,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2734,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2744,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2747,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x274c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x274e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2753,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2754,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2755,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2757,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2763,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x2764,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x2795,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2796,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2797,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x27a1,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x27b0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x27bf,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2934,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2935,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b05,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b06,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b07,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b1b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b1c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x2b50,
        flags: 0,
    },
    EmojiEntry {
        code: 0x2b55,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x3030,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x303d,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x3297,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x3299,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f004,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f0cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f170,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f171,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f17e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f17f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f18e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f191,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f192,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f193,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f194,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f195,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f196,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f197,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f198,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f199,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f19a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f201,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f202,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f21a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f22f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f232,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f233,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f234,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f235,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f236,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f237,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f238,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f239,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f23a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f250,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f251,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f300,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f301,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f302,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f303,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f304,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f305,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f306,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f307,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f308,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f309,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f30f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f310,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f311,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f312,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f313,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f314,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f315,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f316,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f317,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f318,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f319,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f31f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f320,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f321,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f324,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f325,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f326,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f327,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f328,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f329,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f32f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f330,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f331,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f332,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f333,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f334,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f335,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f336,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f337,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f338,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f339,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f33f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f340,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f341,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f342,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f343,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f344,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f345,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f346,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f347,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f348,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f349,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f34f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f350,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f351,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f352,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f353,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f354,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f355,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f356,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f357,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f358,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f359,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f35f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f360,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f361,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f362,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f363,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f364,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f365,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f366,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f367,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f368,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f369,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f36f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f370,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f371,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f372,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f373,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f374,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f375,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f376,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f377,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f378,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f379,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f37f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f380,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f381,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f382,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f383,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f384,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f385,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f386,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f387,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f388,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f389,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f38f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f390,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f391,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f392,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f393,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f396,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f397,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f399,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f39a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f39b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f39e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f39f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a6,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f3a7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3a9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3aa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ab,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ac,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ad,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ae,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3af,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3b9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ba,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3bb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3bc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3bd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3be,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3bf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3c9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ca,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3cb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3cc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3cd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ce,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3d9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3da,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3db,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3dc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3dd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3de,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3df,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e7,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f3e8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3e9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ea,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3eb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ec,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ed,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ee,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ef,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3f9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3fb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3fc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3fd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3fe,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f3ff,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f400,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f401,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f402,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f403,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f404,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f405,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f406,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f407,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f408,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f409,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f40f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f410,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f411,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f412,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f413,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f414,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f415,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f416,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f417,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f418,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f419,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f41f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f420,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f421,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f422,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f423,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f424,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f425,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f426,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f427,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f428,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f429,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f42f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f430,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f431,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f432,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f433,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f434,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f435,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f436,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f437,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f438,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f439,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f43f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f440,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f441,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f442,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f443,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f444,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f445,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f446,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f447,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f448,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f449,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f44f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f450,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f451,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f452,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f453,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f454,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f455,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f456,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f457,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f458,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f459,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f45f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f460,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f461,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f462,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f463,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f464,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f465,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f466,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f467,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f468,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f469,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f46f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f470,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f471,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f472,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f473,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f474,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f475,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f476,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f477,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f478,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f479,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f47a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f47b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f47c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f47d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f47e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f47f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f480,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f481,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f482,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f483,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f484,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f485,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f486,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f487,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f488,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f489,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f48a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f48b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f48c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f48d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f48e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f48f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f490,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f491,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f492,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f493,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f494,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f495,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f496,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f497,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f498,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f499,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f49f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4a1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4a2,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a3,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a4,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a5,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a6,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4a8,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4a9,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4aa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ab,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4ac,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4ad,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4ae,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4af,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f4b0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b1,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4b2,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4b3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4b9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ba,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4bb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4bc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4bd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4be,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4bf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4c9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ca,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4cb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4cc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4cd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ce,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4d9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4da,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4db,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4dc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4dd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4de,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4df,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4e9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ea,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4eb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ec,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ed,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ee,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ef,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f3,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4f4,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4f5,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4f6,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f4f7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4f9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4fb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4fc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4fd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f4ff,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f500,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f501,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f502,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f503,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f504,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f505,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f506,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f507,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f508,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f509,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f50f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f510,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f511,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f512,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f513,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f514,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f515,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f516,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f517,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f518,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f519,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51d,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f51f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f520,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f521,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f522,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f523,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f524,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f525,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f526,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f527,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f528,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f529,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f52f,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f530,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f531,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f532,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f533,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f534,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f535,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f536,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f537,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f538,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f539,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f53a,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f53b,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f53c,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f53d,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f549,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f54a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f54b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f54c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f54d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f54e,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f550,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f551,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f552,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f553,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f554,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f555,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f556,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f557,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f558,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f559,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f55f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f560,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f561,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f562,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f563,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f564,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f565,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f566,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f567,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f56f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f570,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f573,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f574,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f575,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f576,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f577,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f578,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f579,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f57a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f587,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f58a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f58b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f58c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f58d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f590,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f595,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f596,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5a4,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f5a5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5a8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5b1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5b2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5bc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5c2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5c3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5c4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5d2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5d3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5dc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5dd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5de,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5e1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5e3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5e8,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f5ef,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f5f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5fb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5fc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5fd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5fe,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f5ff,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f600,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f601,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f602,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f603,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f604,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f605,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f606,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f607,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f608,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f609,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f60f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f610,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f611,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f612,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f613,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f614,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f615,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f616,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f617,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f618,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f619,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f61f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f620,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f621,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f622,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f623,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f624,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f625,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f626,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f627,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f628,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f629,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f62f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f630,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f631,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f632,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f633,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f634,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f635,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f636,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f637,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f638,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f639,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f63f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f640,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f641,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f642,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f643,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f644,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f645,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f646,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f647,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f648,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f649,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f64a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f64b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f64c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f64d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f64e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f64f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f680,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f681,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f682,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f683,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f684,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f685,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f686,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f687,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f688,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f689,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f68f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f690,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f691,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f692,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f693,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f694,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f695,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f696,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f697,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f698,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f699,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f69f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6a9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6aa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6ab,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6ac,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6ad,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6ae,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6af,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b1,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6b3,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6b5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6b6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6b7,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b8,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6b9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6ba,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6bb,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6bc,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6bd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6be,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6bf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6c0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6c1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6c2,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6c3,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6c4,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6c5,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6cb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6cc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6cd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6ce,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f6d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6d8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6dc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6dd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6de,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6df,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6e9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6eb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6ec,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6f9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6fb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f6fc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f7e0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e1,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e2,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e3,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e4,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e5,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e6,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e7,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e8,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7e9,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7ea,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7eb,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f7f0,
        flags: FLAG_SYMBOLS,
    },
    EmojiEntry {
        code: 0x1f90c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f90d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f90e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f90f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f910,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f911,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f912,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f913,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f914,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f915,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f916,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f917,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f918,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f919,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f91f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f920,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f921,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f922,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f923,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f924,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f925,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f926,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f927,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f928,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f929,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92b,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92c,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92d,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92e,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f92f,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f930,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f931,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f932,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f933,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f934,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f935,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f936,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f937,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f938,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f939,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f93a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f93c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f93d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f93e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f93f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f940,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f941,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f942,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f943,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f944,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f945,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f947,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f948,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f949,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f94f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f950,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f951,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f952,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f953,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f954,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f955,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f956,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f957,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f958,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f959,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f95f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f960,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f961,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f962,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f963,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f964,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f965,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f966,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f967,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f968,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f969,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f96f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f970,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f971,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f972,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f973,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f974,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f975,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f976,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f977,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f978,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f979,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f97a,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f97b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f97c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f97d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f97e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f97f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f980,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f981,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f982,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f983,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f984,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f985,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f986,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f987,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f988,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f989,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f98f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f990,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f991,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f992,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f993,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f994,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f995,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f996,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f997,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f998,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f999,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f99f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9a9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9aa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ab,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ac,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ad,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ae,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9af,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9b9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ba,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9bb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9bc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9bd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9be,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9bf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9c9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ca,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9cb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9cc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9cd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ce,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9cf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d0,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f9d1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9d9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9da,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9db,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9dc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9dd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9de,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9df,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e1,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1f9e2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9e9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ea,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9eb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ec,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ed,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ee,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ef,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9f9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9fa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9fb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9fc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9fd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9fe,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1f9ff,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa70,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa71,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa72,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa73,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa74,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa75,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa76,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa77,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa78,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa79,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa7a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa7b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa7c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa80,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa81,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa82,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa83,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa84,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa85,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa86,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa87,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa88,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa89,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa8a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa8e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa8f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa90,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa91,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa92,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa93,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa94,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa95,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa96,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa97,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa98,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa99,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9a,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9b,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9c,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9d,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9e,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fa9f,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faa9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faaa,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faab,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faac,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faad,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faae,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faaf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fab9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faba,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fabb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fabc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fabd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fabe,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fabf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fac8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1facd,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1face,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1facf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fad9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fada,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fadb,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fadc,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fadf,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fae0,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae1,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae2,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae3,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae4,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae5,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiEntry {
        code: 0x1fae6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fae7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fae8,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1fae9,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faea,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faef,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf0,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf1,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf2,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf3,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf4,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf5,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf6,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf7,
        flags: 0,
    },
    EmojiEntry {
        code: 0x1faf8,
        flags: 0,
    },
];
