// Auto-generated by scripts/generate_emoji_data.py; do not edit manually.
pub const FLAG_SMILEYS_EMOTION: u8 = 1 << 0;
pub const FLAG_SYMBOLS: u8 = 1 << 1;

#[derive(Clone, Copy)]
pub struct EmojiRange {
    pub start: u32,
    pub end: u32,
    pub flags: u8,
}

pub static EMOJI_RANGES: &[EmojiRange] = &[
    EmojiRange {
        start: 0x00a9_u32,
        end: 0x00a9_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x00ae_u32,
        end: 0x00ae_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x203c_u32,
        end: 0x203c_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2049_u32,
        end: 0x2049_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2122_u32,
        end: 0x2122_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2139_u32,
        end: 0x2139_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2194_u32,
        end: 0x2199_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x21a9_u32,
        end: 0x21aa_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x23cf_u32,
        end: 0x23cf_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x23e9_u32,
        end: 0x23ef_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x23f8_u32,
        end: 0x23fa_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x24c2_u32,
        end: 0x24c2_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x25aa_u32,
        end: 0x25ab_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x25b6_u32,
        end: 0x25b6_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x25c0_u32,
        end: 0x25c0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x25fb_u32,
        end: 0x25fe_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2611_u32,
        end: 0x2611_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2620_u32,
        end: 0x2620_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x2622_u32,
        end: 0x2623_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2626_u32,
        end: 0x2626_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x262a_u32,
        end: 0x262a_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x262e_u32,
        end: 0x262f_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2638_u32,
        end: 0x2638_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2639_u32,
        end: 0x263a_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x2640_u32,
        end: 0x2640_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2642_u32,
        end: 0x2642_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2648_u32,
        end: 0x2653_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x267b_u32,
        end: 0x267b_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x267e_u32,
        end: 0x267f_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2695_u32,
        end: 0x2695_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x269b_u32,
        end: 0x269c_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x26a0_u32,
        end: 0x26a0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x26a7_u32,
        end: 0x26a7_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x26aa_u32,
        end: 0x26ab_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x26ce_u32,
        end: 0x26ce_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x26d4_u32,
        end: 0x26d4_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2705_u32,
        end: 0x2705_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2714_u32,
        end: 0x2714_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2716_u32,
        end: 0x2716_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x271d_u32,
        end: 0x271d_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2721_u32,
        end: 0x2721_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2733_u32,
        end: 0x2734_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2747_u32,
        end: 0x2747_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x274c_u32,
        end: 0x274c_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x274e_u32,
        end: 0x274e_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2753_u32,
        end: 0x2755_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2757_u32,
        end: 0x2757_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2763_u32,
        end: 0x2764_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x2795_u32,
        end: 0x2797_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x27a1_u32,
        end: 0x27a1_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x27b0_u32,
        end: 0x27b0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x27bf_u32,
        end: 0x27bf_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2934_u32,
        end: 0x2935_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2b05_u32,
        end: 0x2b07_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2b1b_u32,
        end: 0x2b1c_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x2b55_u32,
        end: 0x2b55_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x3030_u32,
        end: 0x3030_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x303d_u32,
        end: 0x303d_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x3297_u32,
        end: 0x3297_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x3299_u32,
        end: 0x3299_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f170_u32,
        end: 0x1f171_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f17e_u32,
        end: 0x1f17f_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f18e_u32,
        end: 0x1f18e_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f191_u32,
        end: 0x1f19a_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f201_u32,
        end: 0x1f202_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f21a_u32,
        end: 0x1f21a_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f22f_u32,
        end: 0x1f22f_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f232_u32,
        end: 0x1f23a_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f250_u32,
        end: 0x1f251_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f3a6_u32,
        end: 0x1f3a6_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f3e7_u32,
        end: 0x1f3e7_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f479_u32,
        end: 0x1f47b_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f47d_u32,
        end: 0x1f480_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f48b_u32,
        end: 0x1f48c_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f493_u32,
        end: 0x1f49f_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f4a0_u32,
        end: 0x1f4a0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f4a2_u32,
        end: 0x1f4a6_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f4a8_u32,
        end: 0x1f4a9_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f4ab_u32,
        end: 0x1f4ad_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f4af_u32,
        end: 0x1f4af_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f4b1_u32,
        end: 0x1f4b2_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f4db_u32,
        end: 0x1f4db_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f4f3_u32,
        end: 0x1f4f6_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f500_u32,
        end: 0x1f506_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f518_u32,
        end: 0x1f524_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f52f_u32,
        end: 0x1f53d_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f549_u32,
        end: 0x1f549_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f54e_u32,
        end: 0x1f54e_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f573_u32,
        end: 0x1f573_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f5a4_u32,
        end: 0x1f5a4_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f5e8_u32,
        end: 0x1f5e8_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f5ef_u32,
        end: 0x1f5ef_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f600_u32,
        end: 0x1f644_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f648_u32,
        end: 0x1f64a_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f6ab_u32,
        end: 0x1f6ab_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6ad_u32,
        end: 0x1f6b1_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6b3_u32,
        end: 0x1f6b3_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6b7_u32,
        end: 0x1f6bc_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6be_u32,
        end: 0x1f6be_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6c2_u32,
        end: 0x1f6c5_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f6d0_u32,
        end: 0x1f6d0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f7e0_u32,
        end: 0x1f7eb_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f7f0_u32,
        end: 0x1f7f0_u32,
        flags: FLAG_SYMBOLS,
    },
    EmojiRange {
        start: 0x1f90d_u32,
        end: 0x1f90e_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f910_u32,
        end: 0x1f917_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f920_u32,
        end: 0x1f925_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f927_u32,
        end: 0x1f92f_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f970_u32,
        end: 0x1f976_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f978_u32,
        end: 0x1f97a_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f9d0_u32,
        end: 0x1f9d0_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1f9e1_u32,
        end: 0x1f9e1_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
    EmojiRange {
        start: 0x1fae0_u32,
        end: 0x1fae5_u32,
        flags: FLAG_SMILEYS_EMOTION,
    },
];
